import json
from typing import List


def generate_notebook(code_blocks: List[str]) -> str:
    """
    Converts a list of Python code strings into a Jupyter Notebook (.ipynb) JSON string.
    """
    cells = []

    # Add a markdown cell for the title
    cells.append(
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# AutoDS Analysis Notebook\n",
                "This notebook was automatically generated by AutoDS.",
            ],
        }
    )

    for code in code_blocks:
        cells.append(
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": code.splitlines(keepends=True),
            }
        )

    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "codemirror_mode": {"name": "ipython", "version": 3},
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.8.5",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 4,
    }

    return json.dumps(notebook, indent=2)
