import json
import re
from typing import List, Dict, Any


def generate_notebook(session_history: List[Dict[str, Any]]) -> str:
    """
    Converts session history (list of message dicts) into a Jupyter Notebook JSON string.
    Skips 'user' messages. Parses 'assistant' messages into Text (Markdown) and Code cells.
    """
    cells = []

    # Add a markdown cell for the title
    cells.append(
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# AutoDS Analysis Notebook\n",
                "This notebook was automatically generated by AutoDS Agent.",
            ],
        }
    )

    for message in session_history:
        # STRICT RULE: Skip User Queries
        if message.get("role") != "assistant":
            continue

        content = message.get("content", "")
        if not content:
            continue

        # Split content by code blocks
        # 're.split' with capturing group includes the delimiter (code block) in results

        # We want to identify code blocks vs text.
        # Simple regex to find code blocks: ```python(.*?)```

        parts = re.split(r"(```python\s*.*?\s*```)", content, flags=re.DOTALL)

        for part in parts:
            if not part.strip():
                continue

            # Check if this part is a code block
            code_match = re.match(r"```python\s*(.*?)\s*```", part, re.DOTALL)

            if code_match:
                # It's a code block -> Code Cell
                code_content = code_match.group(1).strip()
                cells.append(
                    {
                        "cell_type": "code",
                        "execution_count": None,
                        "metadata": {},
                        "outputs": [],
                        "source": code_content.splitlines(keepends=True),
                    }
                )
            else:
                # It's regular text -> Markdown Cell
                # Clean up any residual markers if necessary, but usually text is clean
                cells.append(
                    {
                        "cell_type": "markdown",
                        "metadata": {},
                        "source": part.strip().splitlines(keepends=True),
                    }
                )

    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "codemirror_mode": {"name": "ipython", "version": 3},
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.8.5",
            },
        },
        "nbformat": 4,
        "nbformat_minor": 4,
    }

    return json.dumps(notebook, indent=2)
